version: "3.7"

services:
  invarch-alice:
    container_name: invarch-alice
    image: invarch/inv4:latest
    build:
      dockerfile: dockerfile
    network_mode: "host"
    ports:
      - "9944:9944"
    command:
      - "--force-authoring"
      - "--collator"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--chain=solo-dev"
      - "--tmp"
      - "--alice"

  invarch-bob:
    container_name: invarch-bob
    image: invarch/inv4:latest
    build:
      dockerfile: dockerfile
    network_mode: "host"
    ports:
      - "9945:9944"
    command:
      - "--force-authoring"
      - "--collator"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--chain=solo-dev"
      - "--tmp"
      - "--bob"
      - "--port=30335"
