[toolchain]
# channel = "nightly-2024-02-06"
channel = "1.74.0"
targets = ["wasm32-unknown-unknown"]
components = [
    "rustfmt",
    "rustc",
    "rust-std",
    "cargo",
    "clippy",
    "llvm-tools",
    "rust-analyzer",
]
profile = "minimal"
