//! Autogenerated weights for pallet_rings
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-16, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Gabriels-MacBook-Pro-3.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./target/release/invarch-collator
    // benchmark
    // pallet
    // --chain=dev
    // --execution=wasm
    // --wasm-execution=compiled
    // --pallet=pallet_rings
    // --extrinsic=*
    // --steps
    // 50
    // --repeat
    // 20
    // --output=../InvArch-Frames/pallet-rings/src/weights.rs
    // --template=weights-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_rings.
pub trait WeightInfo {
	  fn set_maintenance_status() -> Weight;
	  fn send_call(c: u32, ) -> Weight;
	  fn transfer_assets() -> Weight;
	  fn bridge_assets() -> Weight;
  }

  /// Weights for pallet_rings using the Substrate node and recommended hardware.
  pub struct SubstrateWeight<T>(PhantomData<T>);
          impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	            // Storage: Rings ChainsUnderMaintenance (r:0 w:1)
	        fn set_maintenance_status() -> Weight {
		      // Minimum execution time: 14_000 nanoseconds.
		      Weight::from_ref_time(14_000_000)
			        .saturating_add(T::DbWeight::get().writes(1))
	        }
	            // Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	            // Storage: ParachainInfo ParachainId (r:1 w:0)
	            // Storage: ParachainSystem HostConfiguration (r:1 w:0)
	            // Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	            /// The range of component `c` is `[0, 100000]`.
	        fn send_call(c: u32, ) -> Weight {
		      // Minimum execution time: 23_000 nanoseconds.
		      Weight::from_ref_time(25_997_080)
			        // Standard Error: 1
			        .saturating_add(Weight::from_ref_time(712).saturating_mul(c.into()))
			        .saturating_add(T::DbWeight::get().reads(4))
			        .saturating_add(T::DbWeight::get().writes(1))
	        }
	            // Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	            // Storage: ParachainInfo ParachainId (r:1 w:0)
	            // Storage: ParachainSystem HostConfiguration (r:1 w:0)
	            // Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	        fn transfer_assets() -> Weight {
		      // Minimum execution time: 23_000 nanoseconds.
		      Weight::from_ref_time(24_000_000)
			        .saturating_add(T::DbWeight::get().reads(4))
			        .saturating_add(T::DbWeight::get().writes(1))
	        }
	            // Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	            // Storage: ParachainInfo ParachainId (r:1 w:0)
	            // Storage: ParachainSystem HostConfiguration (r:1 w:0)
	            // Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	        fn bridge_assets() -> Weight {
		      // Minimum execution time: 28_000 nanoseconds.
		      Weight::from_ref_time(29_000_000)
			        .saturating_add(T::DbWeight::get().reads(4))
			        .saturating_add(T::DbWeight::get().writes(1))
	        }
  }

  // For backwards compatibility and tests
  impl WeightInfo for () {
	        // Storage: Rings ChainsUnderMaintenance (r:0 w:1)
	    fn set_maintenance_status() -> Weight {
		  // Minimum execution time: 14_000 nanoseconds.
		  Weight::from_ref_time(14_000_000)
			    .saturating_add(RocksDbWeight::get().writes(1))
	    }
	        // Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	        // Storage: ParachainInfo ParachainId (r:1 w:0)
	        // Storage: ParachainSystem HostConfiguration (r:1 w:0)
	        // Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	        /// The range of component `c` is `[0, 100000]`.
	    fn send_call(c: u32, ) -> Weight {
		  // Minimum execution time: 23_000 nanoseconds.
		  Weight::from_ref_time(25_997_080)
			    // Standard Error: 1
			    .saturating_add(Weight::from_ref_time(712).saturating_mul(c.into()))
			    .saturating_add(RocksDbWeight::get().reads(4))
			    .saturating_add(RocksDbWeight::get().writes(1))
	    }
	        // Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	        // Storage: ParachainInfo ParachainId (r:1 w:0)
	        // Storage: ParachainSystem HostConfiguration (r:1 w:0)
	        // Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	    fn transfer_assets() -> Weight {
		  // Minimum execution time: 23_000 nanoseconds.
		  Weight::from_ref_time(24_000_000)
			    .saturating_add(RocksDbWeight::get().reads(4))
			    .saturating_add(RocksDbWeight::get().writes(1))
	    }
	        // Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	        // Storage: ParachainInfo ParachainId (r:1 w:0)
	        // Storage: ParachainSystem HostConfiguration (r:1 w:0)
	        // Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	    fn bridge_assets() -> Weight {
		  // Minimum execution time: 28_000 nanoseconds.
		  Weight::from_ref_time(29_000_000)
			    .saturating_add(RocksDbWeight::get().reads(4))
			    .saturating_add(RocksDbWeight::get().writes(1))
	    }
  }
