[package]
name = 'pallet-dao-staking'
description = 'FRAME pallet for DAO staking'
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
log = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true, optional = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
num-traits = { workspace = true }
pallet-balances = { workspace = true, optional = true }
pallet-message-queue = { workspace = true }
pallet-session = { workspace = true }
pallet-timestamp = { workspace = true, optional = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-staking = { workspace = true }
sp-std = { workspace = true }

pallet-dao-manager = { workspace = true }

cumulus-primitives-core = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
orml-tokens = { workspace = true }
orml-traits = { workspace = true }
xcm = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "cumulus-primitives-core/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "num-traits/std",
    "orml-tokens/std",
    "orml-traits/std",
    "pallet-balances/std",
    "pallet-dao-manager/std",
    "pallet-message-queue/std",
    "pallet-session/std",
    "pallet-timestamp/std",
    "scale-info/std",
    "serde",
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-staking/std",
    "sp-std/std",
    "xcm/std",
    "log/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-dao-manager/runtime-benchmarks",
    "pallet-message-queue/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "sp-staking/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime", "pallet-dao-manager/try-runtime", "sp-runtime/try-runtime"]
