[package]
name = "frame-support-procedural-tools"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Proc macro helpers for procedural macros"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
proc-macro-crate = "3.0.0"
proc-macro2 = "1.0.64"
quote = "1.0.33"
syn = { version = "2.0.53", features = ["full", "visit", "extra-traits"] }
frame-support-procedural-tools-derive = { version = "3.0.0", path = "./derive" }
