[package]
name = 'invarch-primitives'
description = 'InvArch primitives for InvArchh Pallet Library'
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
serde = { workspace = true, optional = true }
codec = { workspace = true }
scale-info = { workspace = true }

frame-system = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }


[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-core/std",
    "frame-system/std",
    "sp-std/std",
    "scale-info/std",
    "sp-io/std",
    "sp-runtime/std",
]
