name: Release binary to existing tag

on:
  workflow_dispatch:
    inputs:
      # Get name of the chain
      chain:
        description: Chain (default = tinkernet)
        required: true
        default: tinkernet
        type: choice
        options:
          - tinkernet
          - invarch

jobs:
  build_binary:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ github.event.inputs.chain }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Setup for checks
      run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler

    - name: Install & display rust toolchain
      run: rustup show

    - name: Build binary
      run: cargo build --release

    - name: Add binary to release
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-name: ${{ github.ref_name }}
        asset-name: '${{ github.event.inputs.chain }}-collator'
        file: 'target/release/${{ github.event.inputs.chain }}-collator'
