name: Release binary to existing tag

on: workflow_dispatch

jobs:
  build_binary:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup for checks
      run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler
    
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      
    - name: Build binary
      run: cargo build --release
      
    - name: Add binary to release
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-name: ${{ github.ref_name }}
        asset-name: 'invarch-collator'
        file: 'target/release/invarch-collator'
        
    - name: Add spec file to release
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-name: ${{ github.ref_name }}
        asset-name: 'tinker-raw.json'
        file: 'res/tinker/tinker-raw.json'
