name: Release binary to existing tag

on: workflow_dispatch

jobs:
  build_binary:
    runs-on: ubuntu-latest
    steps:
    
    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup for checks
      run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler
      
    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed
      
    - name: Build binary
      run: cargo build --release
      
    - name: Add binary to release
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-name: ${{ github.ref_name }}
        asset-name: 'invarch-collator'
        file: 'target/release/invarch-collator'
        
    - name: Add spec file to release
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-name: ${{ github.ref_name }}
        asset-name: 'tinker-raw.json'
        file: 'res/tinker/tinker-raw.json'
