
//! Autogenerated weights for `pallet_rings`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-08-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Gabriels-MacBook-Pro-3.local`, CPU: `<UNKNOWN>`
//! EXECUTION: `Some(Wasm)`, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
    // ./target/release/invarch-collator
    // benchmark
    // pallet
    // --chain=dev
    // --execution=wasm
    // --wasm-execution=compiled
    // --pallet=pallet_rings
    // --extrinsic=*
    // --steps
    // 50
    // --repeat
    // 20
    // --output=../InvArch-Frames/pallet-rings/src/weights.rs
    // --template=weights-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_rings`.
pub trait WeightInfo {
	  fn set_maintenance_status() -> Weight;
	  fn send_call(c: u32, ) -> Weight;
	  fn transfer_assets() -> Weight;
	  fn bridge_assets() -> Weight;
  }

  /// Weights for `pallet_rings` using the Substrate node and recommended hardware.
  pub struct SubstrateWeight<T>(PhantomData<T>);
          impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	            /// Storage: Rings ChainsUnderMaintenance (r:0 w:1)
	            /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	        fn set_maintenance_status() -> Weight {
		      // Proof Size summary in bytes:
		      //  Measured:  `0`
		      //  Estimated: `0`
		      // Minimum execution time: 8_000_000 picoseconds.
		      Weight::from_parts(8_000_000, 0)
			        .saturating_add(T::DbWeight::get().writes(1_u64))
	        }
	            /// Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	            /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	            /// Storage: ParachainInfo ParachainId (r:1 w:0)
	            /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	            /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
	            /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
	            /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
	            /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
	            /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	            /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	            /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	            /// The range of component `c` is `[0, 100000]`.
	        fn send_call(c: u32, ) -> Weight {
		      // Proof Size summary in bytes:
		      //  Measured:  `253`
		      //  Estimated: `4084`
		      // Minimum execution time: 36_000_000 picoseconds.
		      Weight::from_parts(37_257_805, 4084)
			        // Standard Error: 1
			        .saturating_add(Weight::from_parts(2_102, 0).saturating_mul(c.into()))
			        .saturating_add(T::DbWeight::get().reads(7_u64))
			        .saturating_add(T::DbWeight::get().writes(2_u64))
	        }
	            /// Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	            /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	            /// Storage: ParachainInfo ParachainId (r:1 w:0)
	            /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	            /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
	            /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
	            /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
	            /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
	            /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	            /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	            /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	        fn transfer_assets() -> Weight {
		      // Proof Size summary in bytes:
		      //  Measured:  `253`
		      //  Estimated: `4084`
		      // Minimum execution time: 36_000_000 picoseconds.
		      Weight::from_parts(37_000_000, 4084)
			        .saturating_add(T::DbWeight::get().reads(7_u64))
			        .saturating_add(T::DbWeight::get().writes(2_u64))
	        }
	            /// Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	            /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	            /// Storage: ParachainInfo ParachainId (r:1 w:0)
	            /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	            /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
	            /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
	            /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
	            /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
	            /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	            /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	            /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	            /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	        fn bridge_assets() -> Weight {
		      // Proof Size summary in bytes:
		      //  Measured:  `253`
		      //  Estimated: `4084`
		      // Minimum execution time: 43_000_000 picoseconds.
		      Weight::from_parts(44_000_000, 4084)
			        .saturating_add(T::DbWeight::get().reads(7_u64))
			        .saturating_add(T::DbWeight::get().writes(2_u64))
	        }
  }

  // For backwards compatibility and tests.
  impl WeightInfo for () {
	        /// Storage: Rings ChainsUnderMaintenance (r:0 w:1)
	        /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	    fn set_maintenance_status() -> Weight {
		  // Proof Size summary in bytes:
		  //  Measured:  `0`
		  //  Estimated: `0`
		  // Minimum execution time: 8_000_000 picoseconds.
		  Weight::from_parts(8_000_000, 0)
			    .saturating_add(RocksDbWeight::get().writes(1_u64))
	    }
	        /// Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	        /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	        /// Storage: ParachainInfo ParachainId (r:1 w:0)
	        /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	        /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
	        /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
	        /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
	        /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
	        /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	        /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	        /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	        /// The range of component `c` is `[0, 100000]`.
	    fn send_call(c: u32, ) -> Weight {
		  // Proof Size summary in bytes:
		  //  Measured:  `253`
		  //  Estimated: `4084`
		  // Minimum execution time: 36_000_000 picoseconds.
		  Weight::from_parts(37_257_805, 4084)
			    // Standard Error: 1
			    .saturating_add(Weight::from_parts(2_102, 0).saturating_mul(c.into()))
			    .saturating_add(RocksDbWeight::get().reads(7_u64))
			    .saturating_add(RocksDbWeight::get().writes(2_u64))
	    }
	        /// Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	        /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	        /// Storage: ParachainInfo ParachainId (r:1 w:0)
	        /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	        /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
	        /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
	        /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
	        /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
	        /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	        /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	        /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	    fn transfer_assets() -> Weight {
		  // Proof Size summary in bytes:
		  //  Measured:  `253`
		  //  Estimated: `4084`
		  // Minimum execution time: 36_000_000 picoseconds.
		  Weight::from_parts(37_000_000, 4084)
			    .saturating_add(RocksDbWeight::get().reads(7_u64))
			    .saturating_add(RocksDbWeight::get().writes(2_u64))
	    }
	        /// Storage: Rings ChainsUnderMaintenance (r:1 w:0)
	        /// Proof: Rings ChainsUnderMaintenance (max_values: None, max_size: Some(619), added: 3094, mode: MaxEncodedLen)
	        /// Storage: ParachainInfo ParachainId (r:1 w:0)
	        /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	        /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
	        /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
	        /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
	        /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
	        /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	        /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	        /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	        /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	    fn bridge_assets() -> Weight {
		  // Proof Size summary in bytes:
		  //  Measured:  `253`
		  //  Estimated: `4084`
		  // Minimum execution time: 43_000_000 picoseconds.
		  Weight::from_parts(44_000_000, 4084)
			    .saturating_add(RocksDbWeight::get().reads(7_u64))
			    .saturating_add(RocksDbWeight::get().writes(2_u64))
	    }
  }
